//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telefonbuch
{
    using System;
    using System.Collections.Generic;
    
    public partial class KontaktListe
    {
        public int ID { get; set; }
        public string VorName { get; set; }
        public string NachName { get; set; }
        public string NummerR { get; set; }
    }
}
